# Generated by Django 5.2.1 on 2025-05-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='keycloak_user_id',
        ),
    ]
