services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_DB: user
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5431:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
#   postgres:
#     image: postgres:13
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: keycloak
#       POSTGRES_USER: keycloak
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5434:5432"


#   keycloak:
#     image: quay.io/keycloak/keycloak:24.0.1
#     container_name: keycloak
#     command: start-dev
#     ports:
#       - "8080:8080"
#     environment:
#       KC_HOSTNAME: localhost
#       KC_HOSTNAME_PORT: 8080
#       KC_HOSTNAME_STRICT_BACKCHANNEL: false
#       KC_HTTP_ENABLED: true
#       KC_HOSTNAME_STRICT_HTTPS: false
#       KC_HEALTH_ENABLED: true
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin
#       KC_DB: postgres
#       KC_DB_URL: jdbc:postgresql://postgres/keycloak
#       KC_DB_USERNAME: keycloak
#       KC_DB_PASSWORD: password
#     restart: always
#     depends_on:
#       - postgres
#     volumes:
#       - keycloak_data:/opt/keycloak/data

# volumes:
#   keycloak_data:
#   db_data:
#   postgres_data: