# Generated by Django 5.2.1 on 2025-05-30 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('customer_phone', models.CharField(max_length=50)),
                ('product_id', models.UUIDField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='order_order_custome_df6711_idx'), models.Index(fields=['order_number'], name='order_order_order_n_fb1851_idx'), models.Index(fields=['status'], name='order_order_status_2f1723_idx')],
            },
        ),
    ]
