# Generated by Django 5.2.1 on 2025-05-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_order_order_status_2f1723_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_custome_df6711_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
    ]
